### ISSUE TITLE
Cleanup after test has finished

### ISSUE THREAD

**Issue by barbasa** [barbasa/gatling-git#1]
Test is creating directories in _/tmp_ . They need to be cleaned up after each run.
The dictory have this structure: /tmp/test-{user}-{projects}

**Comment by thomasdraebing** [comment]
I would suggest to change the directory model and to decouple it from the Request-classes:
My idea would be a model like this:
`<base-path>/gatling-<timestamp>/<user>/<project>`

`<base-path>`: something like `/tmp` . This should be configurable, which would also improve portability (e.g. use from Windows).
`<timestamp>`: We should avoid clashes between runs, if the finalizer does not do its job for any reason.
`<user>`: each simulated user should have its own workspace to avoid clashes between them
`<project>`: should be clear ;-)

This way should be much easier to navigate. We should also decouple the definition of the directory structure from the actual Requests. Then we can have a global finalizer knowing what to delete outside the Request-class, which is currently the only place, where the path is defined.

**Comment by thomasdraebing** [comment]
view change: https://review.gerrithub.io/c/barbasa/gatling-git/+/454335
